FROM node:20 AS builder

WORKDIR /app

ARG NEXT_PUBLIC_DIRECTUS_URL
ARG NEXT_PUBLIC_API_BASE_URL
ARG DIRECTUS_INTERNAL_URL
ARG DIRECTUS_STATIC_TOKEN
ARG API_TOKEN
ARG API_TIMEOUT_MS
ARG NEXT_PUBLIC_MAPBOX_API_KEY
ARG NEXT_PUBLIC_MAPBOX_STYLE
ARG NEXT_PUBLIC_RECAPTCHA_SITE_KEY
ARG RECAPTCHA_SECRET_KEY

ENV NEXT_PUBLIC_DIRECTUS_URL=$NEXT_PUBLIC_DIRECTUS_URL \
    NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL \
    DIRECTUS_INTERNAL_URL=$DIRECTUS_INTERNAL_URL \
    DIRECTUS_STATIC_TOKEN=$DIRECTUS_STATIC_TOKEN \
    API_TOKEN=$API_TOKEN \
    API_TIMEOUT_MS=$API_TIMEOUT_MS \
    NEXT_PUBLIC_MAPBOX_API_KEY=$NEXT_PUBLIC_MAPBOX_API_KEY \
    NEXT_PUBLIC_MAPBOX_STYLE=$NEXT_PUBLIC_MAPBOX_STYLE \
    NEXT_PUBLIC_RECAPTCHA_SITE_KEY=$NEXT_PUBLIC_RECAPTCHA_SITE_KEY \
    RECAPTCHA_SECRET_KEY=$RECAPTCHA_SECRET_KEY

COPY package.json package-lock.json ./

RUN npm install --force

COPY . .

RUN npm run build

FROM node:20

WORKDIR /app

ARG NEXT_PUBLIC_DIRECTUS_URL
ARG NEXT_PUBLIC_API_BASE_URL
ARG DIRECTUS_INTERNAL_URL
ARG DIRECTUS_STATIC_TOKEN
ARG API_TOKEN
ARG API_TIMEOUT_MS
ARG NEXT_PUBLIC_MAPBOX_API_KEY
ARG NEXT_PUBLIC_MAPBOX_STYLE
ARG NEXT_PUBLIC_RECAPTCHA_SITE_KEY
ARG RECAPTCHA_SECRET_KEY

COPY --from=builder /app/package.json /app/package-lock.json /app/
COPY --from=builder /app/.next /app/.next
COPY --from=builder /app/public /app/public
COPY --from=builder /app/node_modules /app/node_modules

ENV NEXT_PUBLIC_DIRECTUS_URL=$NEXT_PUBLIC_DIRECTUS_URL \
    NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL \
    DIRECTUS_INTERNAL_URL=$DIRECTUS_INTERNAL_URL \
    DIRECTUS_STATIC_TOKEN=$DIRECTUS_STATIC_TOKEN \
    API_TOKEN=$API_TOKEN \
    API_TIMEOUT_MS=$API_TIMEOUT_MS \
    NEXT_PUBLIC_MAPBOX_API_KEY=$NEXT_PUBLIC_MAPBOX_API_KEY \
    NEXT_PUBLIC_MAPBOX_STYLE=$NEXT_PUBLIC_MAPBOX_STYLE \
    NEXT_PUBLIC_RECAPTCHA_SITE_KEY=$NEXT_PUBLIC_RECAPTCHA_SITE_KEY \
    RECAPTCHA_SECRET_KEY=$RECAPTCHA_SECRET_KEY

EXPOSE 3000

CMD ["npm", "start"]
