name: categorizabrasil-stack

services:
  directus-database:
    image: postgis/postgis:16-master
    restart: ${RESTART_POLICY:-unless-stopped}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - categorizanet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$${POSTGRES_USER}\" -d \"$${POSTGRES_DB}\" -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  directus-cache:
    image: redis:6
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - categorizanet
    healthcheck:
      test: ["CMD-SHELL", "[ $$(redis-cli ping) = 'PONG' ]"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  directus-minio:
    image: minio/minio:latest
    restart: ${RESTART_POLICY:-unless-stopped}
    command: server /data --console-address ":9001"
    networks:
      - categorizanet
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "${MINIO_API_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  directus-minio-setup:
    image: minio/mc:latest
    depends_on:
      directus-minio:
        condition: service_started
    networks:
      - categorizanet
    restart: "no"
    entrypoint: >
      /bin/sh -c "
        until mc alias set minio http://directus-minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}; do
          sleep 2;
        done;
        mc mb -p minio/${MINIO_BUCKET} || true;
        exit 0;
      "

  directus:
    image: directus/directus:11.12.0
    restart: ${RESTART_POLICY:-unless-stopped}
    depends_on:
      directus-database:
        condition: service_healthy
      directus-cache:
        condition: service_healthy
      directus-minio-setup:
        condition: service_completed_successfully
    ports:
      - "8055:8055"
    networks:
      - categorizanet
    environment:
      SECRET: ${DIRECTUS_SECRET}
      PUBLIC_URL: ${PUBLIC_URL}
      STORAGE_S3_ROOT: ${STORAGE_S3_ROOT}
      TRUST_PROXY: "true"
      WEBSOCKETS_ENABLED: "true"

      DB_CLIENT: "pg"
      DB_HOST: directus-database
      DB_PORT: "5432"
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

      CACHE_ENABLED: ${CACHE_ENABLED}
      CACHE_AUTO_PURGE: ${CACHE_AUTO_PURGE}
      CACHE_STORE: "redis"
      REDIS: "redis://directus-cache:6379"

      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

      CORS_ENABLED: "true"
      CORS_ORIGIN: ${CORS_ORIGIN}

      STORAGE_LOCATIONS: "local,s3"
      DEFAULT_STORAGE: "s3"

      # local (opcional)
      STORAGE_LOCAL_DRIVER: "local"
      STORAGE_LOCAL_ROOT: "/directus/uploads"

      # s3 (MinIO)
      STORAGE_S3_DRIVER: "s3"
      STORAGE_S3_BUCKET: ${MINIO_BUCKET}
      STORAGE_S3_KEY: ${MINIO_ROOT_USER}
      STORAGE_S3_SECRET: ${MINIO_ROOT_PASSWORD}
      STORAGE_S3_REGION: "us-east-1"
      STORAGE_S3_ENDPOINT: "http://directus-minio:9000"
      STORAGE_S3_FORCE_PATH_STYLE: "true"

    volumes:
      - ../cms/extensions:/directus/extensions  

  app:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_DIRECTUS_URL: ${NEXT_PUBLIC_DIRECTUS_URL}
        DIRECTUS_INTERNAL_URL: ${DIRECTUS_INTERNAL_URL}
        DIRECTUS_STATIC_TOKEN: ${DIRECTUS_STATIC_TOKEN}
        API_TIMEOUT_MS: ${API_TIMEOUT_MS}
        NEXT_PUBLIC_MAPBOX_API_KEY: ${NEXT_PUBLIC_MAPBOX_API_KEY}
        NEXT_PUBLIC_MAPBOX_STYLE: ${NEXT_PUBLIC_MAPBOX_STYLE}
    restart: ${RESTART_POLICY:-unless-stopped}
    environment:
      NODE_ENV: ${NODE_ENV}
      NEXT_PUBLIC_DIRECTUS_URL: ${NEXT_PUBLIC_DIRECTUS_URL}
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
      DIRECTUS_INTERNAL_URL: ${DIRECTUS_INTERNAL_URL}
      DIRECTUS_STATIC_TOKEN: ${DIRECTUS_STATIC_TOKEN}
      API_TOKEN: ${API_TOKEN}
      API_TIMEOUT_MS: ${API_TIMEOUT_MS}
      NEXT_PUBLIC_MAPBOX_API_KEY: ${NEXT_PUBLIC_MAPBOX_API_KEY}
      NEXT_PUBLIC_MAPBOX_STYLE: ${NEXT_PUBLIC_MAPBOX_STYLE}
    depends_on:
      directus:
        condition: service_started
    ports:
      - "3001:3000"
    labels:
      - traefik.enable=true
      - traefik.http.routers.categorizabrasil.rule=Host(`categorizabrasil.com.br`,`www.categorizabrasil.com.br`)
      - traefik.http.routers.categorizabrasil.entrypoints=websecure
      - traefik.http.routers.categorizabrasil.tls=true
      - traefik.http.services.categorizabrasil.loadbalancer.server.port=3000
    container_name: site-categoriza-prod
    networks:
      - categorizanet
      - dokploy-network
networks:
  categorizanet:
    driver: bridge
  dokploy-network:
    external: true

volumes:
  pgdata:
  minio_data:
