name: categorizabrasil-stack

services:
  directus-database:
    image: postgis/postgis:16-master
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ../cms/data/database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$${POSTGRES_USER}\" -d \"$${POSTGRES_DB}\" -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  directus-cache:
    image: redis:6
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "[ $$(redis-cli ping) = 'PONG' ]"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  directus-minio:
    image: minio/minio:latest
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "${MINIO_API_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"
    volumes:
      - ../cms/data/minio:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  directus-minio-setup:
    image: minio/mc:latest
    depends_on:
      directus-minio:
        condition: service_started
    restart: "no"
    entrypoint: >
      /bin/sh -c "
        until mc alias set minio http://directus-minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}; do
          sleep 2;
        done;
        mc mb -p minio/${MINIO_BUCKET} || true;
        exit 0;
      "

  directus:
    image: directus/directus:11.12.0
    restart: unless-stopped
    depends_on:
      directus-database:
        condition: service_healthy
      directus-cache:
        condition: service_healthy
      directus-minio-setup:
        condition: service_completed_successfully
    ports:
      - "8055:8055"
    environment:
      # Segurança / URL
      SECRET: ${DIRECTUS_SECRET}
      PUBLIC_URL: ${PUBLIC_URL}
      TRUST_PROXY: "true"
      WEBSOCKETS_ENABLED: "true"

      # Banco
      DB_CLIENT: "pg"
      DB_HOST: directus-database
      DB_PORT: "5432"
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

      CACHE_ENABLED: ${CACHE_ENABLED}
      CACHE_AUTO_PURGE: ${CACHE_AUTO_PURGE}
      CACHE_STORE: "redis"
      REDIS_URL: "redis://directus-cache:6379"

      # Admin bootstrap (remover depois que criar o usuário)
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

      # CORS
      CORS_ENABLED: "true"
      CORS_ORIGIN: ${CORS_ORIGIN}

      # Cookies (produção)
      REFRESH_TOKEN_COOKIE_SECURE: "true"
      REFRESH_TOKEN_COOKIE_SAME_SITE: "lax"
      REFRESH_TOKEN_COOKIE_DOMAIN: "painel.categorizabrasil.com.br"
      SESSION_COOKIE_SECURE: "true"
      SESSION_COOKIE_SAME_SITE: "lax"
      SESSION_COOKIE_DOMAIN: "painel.categorizabrasil.com.br"

      # Extensões
      EXTENSIONS_PATH: "./extensions"
      EXTENSIONS_AUTO_RELOAD: "false"

      # CSP mínima
      CONTENT_SECURITY_POLICY_DIRECTIVES__FRAME_SRC: "https://*.youtube.com,https://*.vimeo.com,https://*.wistia.net,https://*.loom.com"

      # Armazenamento (MinIO)
      STORAGE_LOCATIONS: "s3"
      STORAGE_DEFAULT: "s3"
      STORAGE_S3_DRIVER: "s3"
      STORAGE_S3_BUCKET: ${STORAGE_S3_BUCKET}
      STORAGE_S3_KEY: ${STORAGE_S3_KEY}
      STORAGE_S3_SECRET: ${STORAGE_S3_SECRET}
      STORAGE_S3_ENDPOINT: "http://directus-minio:9000"
      STORAGE_S3_REGION: "us-east-1"
      STORAGE_S3_FORCE_PATH_STYLE: "true"
      STORAGE_S3_ROOT: "uploads"
      STORAGE_S3_PUBLIC_URL: ${STORAGE_S3_PUBLIC_URL}
    volumes:
      - ../cms/extensions:/directus/extensions

  app:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_DIRECTUS_URL: ${NEXT_PUBLIC_DIRECTUS_URL}
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
        DIRECTUS_INTERNAL_URL: ${DIRECTUS_INTERNAL_URL}
        DIRECTUS_STATIC_TOKEN: ${DIRECTUS_STATIC_TOKEN}
        API_TOKEN: ${API_TOKEN}
        API_TIMEOUT_MS: ${API_TIMEOUT_MS}
        NEXT_PUBLIC_MAPBOX_API_KEY: ${NEXT_PUBLIC_MAPBOX_API_KEY}
        NEXT_PUBLIC_MAPBOX_STYLE: ${NEXT_PUBLIC_MAPBOX_STYLE}
    environment:
      NODE_ENV: ${NODE_ENV}
      NEXT_PUBLIC_DIRECTUS_URL: ${NEXT_PUBLIC_DIRECTUS_URL}
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
      DIRECTUS_INTERNAL_URL: ${DIRECTUS_INTERNAL_URL}
      DIRECTUS_STATIC_TOKEN: ${DIRECTUS_STATIC_TOKEN}
      API_TOKEN: ${API_TOKEN}
      API_TIMEOUT_MS: ${API_TIMEOUT_MS}
      NEXT_PUBLIC_MAPBOX_API_KEY: ${NEXT_PUBLIC_MAPBOX_API_KEY}
      NEXT_PUBLIC_MAPBOX_STYLE: ${NEXT_PUBLIC_MAPBOX_STYLE}
    depends_on:
      directus:
        condition: service_started
    ports:
      - "3001:3000"
    container_name: site-categoriza-prod
