name: categorizabrasil-stack

env_file:
  - ../.env

services:
  directus-database:
    image: postgis/postgis:16-master
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      # data persistente dentro do CMS
      - ../cms/data/database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$${POSTGRES_USER}\" -d \"$${POSTGRES_DB}\" -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  directus-cache:
    image: redis:6
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "[ $$(redis-cli ping) = 'PONG' ]"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  directus-minio:
    image: minio/minio:latest
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "${MINIO_API_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"
    volumes:
      # data persistente dentro do CMS
      - ../cms/data/minio:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  directus-minio-setup:
    image: minio/mc:latest
    depends_on:
      directus-minio:
        condition: service_started
    restart: "no"
    entrypoint: >
      /bin/sh -c "
        until mc alias set minio http://directus-minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}; do
          sleep 2;
        done;
        mc mb -p minio/${MINIO_BUCKET} || true;
        exit 0;
      "

  directus:
    image: directus/directus:11.12.0
    restart: unless-stopped
    depends_on:
      directus-database:
        condition: service_healthy
      directus-cache:
        condition: service_healthy
      directus-minio-setup:
        condition: service_completed_successfully
    ports:
      - "8055:8055"
    env_file:
      - ../.env
    volumes:
      - ../cms/extensions:/directus/extensions

  app:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_DIRECTUS_URL: ${NEXT_PUBLIC_DIRECTUS_URL}
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
        DIRECTUS_INTERNAL_URL: ${DIRECTUS_INTERNAL_URL}
        DIRECTUS_STATIC_TOKEN: ${DIRECTUS_STATIC_TOKEN}
        API_TOKEN: ${API_TOKEN}
        API_TIMEOUT_MS: ${API_TIMEOUT_MS}
        NEXT_PUBLIC_MAPBOX_API_KEY: ${NEXT_PUBLIC_MAPBOX_API_KEY}
        NEXT_PUBLIC_MAPBOX_STYLE: ${NEXT_PUBLIC_MAPBOX_STYLE}
    environment:
      NODE_ENV: ${NODE_ENV}
      NEXT_PUBLIC_DIRECTUS_URL: ${NEXT_PUBLIC_DIRECTUS_URL}
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
      DIRECTUS_INTERNAL_URL: ${DIRECTUS_INTERNAL_URL}
      DIRECTUS_STATIC_TOKEN: ${DIRECTUS_STATIC_TOKEN}
      API_TOKEN: ${API_TOKEN}
      API_TIMEOUT_MS: ${API_TIMEOUT_MS}
      NEXT_PUBLIC_MAPBOX_API_KEY: ${NEXT_PUBLIC_MAPBOX_API_KEY}
      NEXT_PUBLIC_MAPBOX_STYLE: ${NEXT_PUBLIC_MAPBOX_STYLE}
    depends_on:
      directus:
        condition: service_started
    ports:
      - "3001:3000"
    container_name: site-categoriza-prod

volumes:
  directus_db:
  minio_data:
